version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petitions_app
    ports:
      - "5556:5432"
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: petitions_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: petitions_db
    ports:
      - "5555:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
