// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Petition struct {
	ID          int32         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	NumberVotes sql.NullInt32 `json:"number_votes"`
	UserID      int32         `json:"user_id"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type Vote struct {
	ID         int32        `json:"id"`
	UserID     int32        `json:"user_id"`
	PetitionID int32        `json:"petition_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
}
